### ISSUE TITLE
로그인 페이지 기능 테스트 작성

### ISSUE THREAD

**Issue by odd02311** [odd02311/board_admin_project#30]
로그인 기능을 구현하기 위해 테스트의 필요성을 검토 및 어드민 회원기능과 카카오 Oauth 인증을 준비

## Todo

- [ ] 로그인 설정 및 테스트 검토
- [ ] 관리자 회원 기능 검토
- [ ] 카카오 Oauth 인증 준비 및 테스트 검토
