### ISSUE TITLE
게시글 관리 페이지 구현

### ISSUE THREAD

**Issue by odd02311** [odd02311/board_admin_project#33]
게시글 관리 페이지 구현

## Todo

- [ ] 게시판 프로젝트
    - [ ] API 호출이 가능하도록 인증 설정 변경
    - [ ] Data REST API 설정 검토
    - [ ] 테스트용 계정 추가
- [ ] 게시글, 댓글 상세 내용을 보기 위한 모당(Modal) 추가
- [ ] 기본 에러 페이지 구현
